name: Deploy

on:
  workflow_dispatch:

env:
  PROJECT_ID: bugtracker-demo
  REGION: southamerica-west1

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify Authentication
        run: |
          gcloud auth list

      - name: Verify Artifact Registry Access
        run: |
          gcloud artifacts repositories list \
            --location=$REGION

      - name: Configure Docker
        run: |
          gcloud auth configure-docker southamerica-west1-docker.pkg.dev --quiet

      - name: Build Backend Image
        working-directory: ./bugtracker-backend
        run: |
          docker build \
            -t southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/bugtracker-repo/backend:githubactions-test \
            .

      - name: Push Backend Image
        run: |
          docker push \
            southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/bugtracker-repo/backend:githubactions-test

      - name: Verify Backend Image Exists
        run: |
          gcloud artifacts docker images list \
            southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/bugtracker-repo/backend

      - name: Deploy Backend
        run: |
          gcloud run deploy bugtracker-backend \
            --image southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/bugtracker-repo/backend:githubactions-test \
            --platform managed \
            --region southamerica-west1 \
            --allow-unauthenticated

      - name: Backend Smoke Test
        run: |
          echo "Checking deployed backend..."

          HTTP_CODE=$(curl --fail -s \
            -o response.json \
            -w "%{http_code}" \
            https://bugtracker-backend-804706805992.southamerica-west1.run.app/api/health)

          echo "HTTP Status: $HTTP_CODE"

          cat response.json

          test "$HTTP_CODE" = "200"

          grep -qi '"status":"ok"' response.json
          
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Build Frontend Image
        working-directory: ./bugtracker-frontend
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=https://bugtracker-backend-804706805992.southamerica-west1.run.app \
            -t southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/bugtracker-repo/frontend:githubactions-test \
            .
      
      - name: Push Frontend Image
        run: |
          docker push \
            southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/bugtracker-repo/frontend:githubactions-test

      - name: Verify Frontend Image Exists
        run: |
          gcloud artifacts docker images list \
            southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/bugtracker-repo/frontend

      - name: Deploy Frontend
        run: |
          gcloud run deploy bugtracker-frontend \
            --image southamerica-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/bugtracker-repo/frontend:githubactions-test \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated

      - name: Frontend Smoke Test
        run: |
          echo "Checking deployed frontend..."

          HTTP_CODE=$(curl --fail -s \
            -o frontend.html \
            -w "%{http_code}" \
            https://bugtracker-frontend-804706805992.southamerica-west1.run.app)

          echo "HTTP Status: $HTTP_CODE"

          test "$HTTP_CODE" = "200"

          grep -qi "<html" frontend.html